In [1]:
import scipy.stats as stats
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from hypothesis_testing_pipeline import *

In [2]:
dummy_data = pd.read_csv('dummy_data.csv', header=None)
dummy_data_transposed = dummy_data.transpose()
hypo_0 = dummy_data_transposed.iloc[:2,:].to_numpy()
hypo_1 = dummy_data_transposed.iloc[1:,:].to_numpy()

In [3]:
hypo_0

array([[2.6, 1.8, 2.6, 2.6, 2.4, 1. ],
       [2.6, 2. , 2.6, 2.6, 2.4, 1.6]])

In [4]:
hypo_1

array([[2.6, 2. , 2.6, 2.6, 2.4, 1.6],
       [2.6, 1.8, 2.6, 2.6, 2.4, 1. ]])

In [5]:
assert type(hypo_0) is np.ndarray and type(hypo_1) is np.ndarray

# Hypothesis checking

In [6]:
HypothesisTester(hypo_0, is_tost=True, is_pair=False, normality=True).print_results()

[2.6 2.  2.6 2.6 2.4 1.6]
T-test TOST
0.004774102433613086
p-value: 0.004774102433613086, reject_alternative: False


In [7]:
HypothesisTester(hypo_1,is_pair=False, normality=True).print_results()

T-test
0.3404390967413118
statistic: 0.42352354988762664, p-value: 0.3404390967413118, reject_alternative: True


In [8]:
arr = np.array([[2.6, 1.8, 2.6, 2.6, 2.4, 1. ], [2.6, 1.8, 2.6, 2.6, 2.4, 1. ]])

In [9]:
arr

array([[2.6, 1.8, 2.6, 2.6, 2.4, 1. ],
       [2.6, 1.8, 2.6, 2.6, 2.4, 1. ]])

In [10]:
diff = 0.05

In [11]:
arr[0] - diff

array([2.55, 1.75, 2.55, 2.55, 2.35, 0.95])